#!/bin/sh

if [ -z "${QUIXOTE_HOME}" ]
then
  echo "QUIXOTE_HOME is unset" 1>&2
  exit 1
fi

exec /usr/bin/env java \
-p "${QUIXOTE_HOME}/lib" \
-m com.io7m.quixote.main/com.io7m.quixote.main.Main \
"$@"
